# Generated by Django 3.0.7 on 2020-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grz', models.CharField(max_length=9, unique=True)),
                ('model', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=5)),
                ('fuel_type', models.CharField(max_length=5)),
                ('lease_payment', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('mileage', models.IntegerField(null=True)),
            ],
        ),
    ]
