# Generated by Django 3.0.7 on 2020-06-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.IntegerField()),
                ('amortiz', models.IntegerField()),
                ('tyres', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('driver', models.CharField(max_length=50)),
                ('shifts', models.IntegerField()),
                ('totalCred', models.IntegerField()),
                ('totalDeb', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('cash', models.IntegerField()),
                ('cash_flow', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='last_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='next_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='to_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe', models.IntegerField()),
                ('profit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taxi.Report')),
            ],
        ),
        migrations.CreateModel(
            name='TO_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_type', models.IntegerField()),
                ('mileage_current', models.IntegerField()),
                ('mileage_next', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taxi.Car', to_field='grz')),
            ],
            options={
                'unique_together': {('car', 'to_type')},
            },
        ),
    ]
