# Generated by Django 3.0.7 on 2020-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_auto_20200624_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
